---
title: "Integration of in vitro hGPCs and Fetal scRNA-seq"
author: "John Mariani"
date: "07/30/2025"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```


```{r, echo = TRUE, message=FALSE, warning=FALSE}

library(Seurat)
library(scPlottingTools)
library(ggplot2)
library(tidyr)
library(dplyr)
library(MAST)
library(plyr)
library(xlsx)
library(patchwork)
library(ggplot2)
library(scales)
library(ggVennDiagram)
library(data.table)
library(slingshot)
library(tradeSeq)
library(tidyr)
library(dplyr)
library(plyr)
library(magrittr)
library(viridis)
library(tidyr)
library(EnhancedVolcano)
library(ggalluvial)



axisTitleSize <- 20
axisTextSize <- 18
labelFont = 18
titleFont = 24
tagSize = 34

source("Scripts/HelperFunctions.R")

theme_manuscript <-  theme(axis.text = element_text(size = axisTextSize), 
        axis.title = element_text(size = axisTitleSize), 
        title = element_text(size = titleFont), 
        legend.title = element_text(size = axisTitleSize),
        legend.text = element_text(size = axisTitleSize),
        plot.tag = element_text(size = tagSize),
        plot.title = element_text(size = titleFont))

manuscriptPalette <- c("In Vivo" = "red2", 
                       "In Vitro - GPC Stage" = "#2E30FF",
                       "NPC" = "magenta",
                       "GPC1" = "forestgreen",
                       "GPC2" = "darkorange",
                       "GPC3" = "firebrick2",
                       "GPC4" = "turquoise",
                       "Astrocyte" = "dodgerblue2",
                       "imOL" = "gold",
                       "maOL" = "darkorchid4",
                       "GPC" = "turquoise",
                       "imAstrocyte" = "firebrick2",
                       "cGPC" = "darkorange",
                       "cAPC" = "forestgreen")




```

## Import Fetal and in vitro scRNA-seq data
```{r}

invitroInvivo <- readRDS("output/RDS/invitroInvivo.rds")

invitro <- subset(invitroInvivo, subset = stage == "In Vitro - GPC Stage")
invitro <- subset(invitro, subset = cellType %in% c("NPC", "GPC1", "GPC2", "GPC3", "GPC4", "imOL"))
invitro$cellType <- droplevels(invitro$cellType)


external <- readRDS("data_for_import/External/VanBruggen/scRNA_human_dev.rds")
external <- UpdateSeuratObject(external)

table(external$Clusters)
external <- subset(external, subset = Clusters %not in% c("Endothelial", "Microglia", "U", "VLMCs", "Radial Glia VLMC primed?"))
external$Clusters <- droplevels(external$Clusters)

DefaultAssay(external) <- "RNA"
external <- NormalizeData(external)

DefaultAssay(invitro) <- "RNA"
invitro <- NormalizeData(invitro)

```


## Subset to common genes and then scTransform datasets individually
```{r}

genes_external <- rownames(external)
genes_invitro <- rownames(invitro)

common_genes <- intersect(genes_external, genes_invitro)

externalFilt<- subset(external, features = common_genes)

invitroFilt <- subset(invitro, features = common_genes)

externalFilt$orig.ident <- externalFilt$Sample

mergedBoth <- merge(externalFilt, invitroFilt)
mergedBoth <- SplitObject(mergedBoth, split.by = "orig.ident")
mergedBoth <- lapply(mergedBoth, SCTransform, verbose = T)

```


## Integrate data across captures
```{r}


features <- SelectIntegrationFeatures(object.list = mergedBoth)

mergedBoth <- PrepSCTIntegration(object.list = mergedBoth, anchor.features = features)

mergedBoth <- lapply(X = mergedBoth, FUN = RunPCA, features = features)

anchors <- FindIntegrationAnchors(object.list = mergedBoth, normalization.method = "SCT",
    anchor.features = features, dims = 1:30, reduction = "rpca", k.anchor = 20)


integrated <- IntegrateData(anchorset = anchors, dims = 1:30)

# Integrate the data
integrated <- ScaleData(integrated, verbose = FALSE)
integrated <- RunPCA(integrated, npcs = 30, verbose = FALSE)
integrated <- RunUMAP(integrated, reduction = "pca", dims = 1:30)
integrated <- FindNeighbors(integrated, reduction = "pca", dims = 1:30)
integrated <- FindClusters(integrated, resolution = 0.5)


integrated$stage <- ifelse(!is.na(integrated$stage), yes = "In Vitro - GPC Stage", no = "Fetal")

#saveRDS(integrated, "output/RDS/integratedVanBrueggen.rds")

```


## Predict labels from external data set and transfer to our hGPC data
```{r}

#integrated <- readRDS("output/RDS/integratedVanBrueggen.rds")
integrated$cellType <- factor(integrated$cellType, c("NPC", "GPC1", "GPC2", "GPC3", "GPC4", "imOL"))

groupDF <- data.frame(Level1 = unique(integrated$Level1)[1:7], group = NA)
groupDF$Level1

groupDF$group <- c("NPC", "Early IN", "RG", "Early EN", "Glioblast", "OPC", "Early IN")

integrated$group <- plyr::mapvalues(integrated$Level1, from = groupDF$Level1, to = groupDF$group)

invitroInt <- subset(integrated, subset = stage != "Fetal")
externalInt <- subset(integrated, subset = stage == "Fetal")



((DimPlotCustom(externalInt, group.by = "group", label = T) + ggtitle("8-10wk GA Fetal - Van Brueggen et al 2022") + guides(fill = guide_legend(override.aes = list(size = 5)))) |
(DimPlotCustom(invitroInt, group.by = "cellType", label = T) + ggtitle("In vitro - GPC Stage") + guides(fill = guide_legend(override.aes = list(size = 5))))) & theme_manuscript & labs(fill = "Cell Type")



DefaultAssay(externalInt)
DefaultAssay(invitroInt)


DefaultAssay(integrated) <- "integrated"



anchors <- FindTransferAnchors(
  reference = externalInt, # Use the full integrated object as the source for anchor finding
  query = invitroInt,     # Use the full integrated object as the target
  reference.assay = "integrated",    # Specify the assay used for integration
  query.assay = "integrated",
  reduction = "rpca",                 # Or "rpca", depending on your integration method
  dims = 1:30                        # Number of dimensions to use
)

##

predictions <- TransferData(
  anchorset = anchors,
  refdata = externalInt$group, # This should be the cell type column from your original dataset1
  query = invitroInt,
  dims = 1:30,
  weight.reduction = "rpca.ref"
)

table(predictions$predicted.id, predictions$cellType)

round(prop.table(table(predictions$predicted.id, predictions$cellType), margin = 2)*100,1)


```



```{r}



integrated <- AddMetaData(
  object = integrated,
  metadata = predictions$predicted.id,
  col.name = "predicted.id"
)

round((prop.table(table(integrated$predicted.id, integrated$cellType), margin = 2)*100),1)


integrated <- AddMetaData(
  object = integrated,
  metadata = predictions$predicted.id.score, 
  col.name = "predicted.score"
)


integrated$predicted.id <- factor(integrated$predicted.id, levels = c("Early IN", "Early EN", "NPC", "RG", "Glioblast", "OPC"))

saveRDS(integrated, "output/RDS/integratedVanBruggen.rds")



```




```{r}

sessionInfo()


```

